### ISSUE TITLE
Use Pep8

### ISSUE THREAD

**Issue by thodrek** [HoloClean/HoloClean-Legacy-deprecated#11]
https://www.python.org/dev/peps/pep-0008/

**Comment by gmichalo** [comment]
To download pep8 type on your environment:

pip install pep8

In order to use pep8 for a python program (example.py):
pep8 --first example.py

In order to see the source code for each error:
pep8 --show-source example.py

**Comment by thodrek** [comment]
The current code is not passing pep8! Fix this!

**Comment by JVonderwell** [comment]
now passes everything except 80 chars per line
