### ISSUE TITLE
Parser_Interface allow more tuple names and tuple amounts

### ISSUE THREAD

**Issue by ah89** [HoloClean/HoloClean-Legacy-deprecated#135]
In line 52 it considered that user put t1,t2 which wrong it should use processed dc which is output of dcparser.get_anded_string(conditionInd='all')

**Comment by j48zheng** [comment]
Not a bug, but it's a feature that we would like to have in the future

**Comment by j48zheng** [comment]
We now allow any tuple names, and suppoert 1 or 2 tuple amounts
