### ISSUE TITLE
Review the project filing

### ISSUE THREAD

**Issue by ah89** [HoloClean/HoloClean-Legacy-deprecated#15]
the learn folder added , please review and comment if a change is needed?

**Comment by thodrek** [comment]
Comments and changes on the structure:
1) Rename injesterbox.py to dataingestor.py (we need names that we understand)
2) Featurization and Errordetection are perfect
3) I do not like the "sparselr" file. We need to have an inferenceengine.py file (at the same level of dataengine.py). Then the inference engine takes two things: a model and a learning backend to run it against. The sparselr will be a model defined as a separate class and written in the inferenceengine.py file. Namely the inferenceengine.py file will contain at least two classes: InferenceEngine and SparseLR. We then need connectors that will translate the SparseLR thing to Tensorflow and Pytorch.

@Ihabilyas Thoughts will be highly appreciated.

**Comment by thodrek** [comment]
@ah89 I want you to discuss the design suggested above with everybody but especially @gmichalo (@j48zheng is also a good candidate) and send me everyone's thoughts.

**Comment by ah89** [comment]
For now we made the changes that mentioned on the comment still need thoughts, And we will discuss it in meeting  **4:00pm 18 Sep**
