### ISSUE TITLE
Wrangling Domains

### ISSUE THREAD

**Issue by Ihabilyas** [HoloClean/HoloClean-Legacy-deprecated#177]
We need to wrangle domains BEFORE holoclean.
This allows us to handle
1) typos
2) wring granularity
3 quantization 
and others..
Holoclean picks the right index in the domain instead of the right value
this also simplifies ground truth comparison 
@thodrek mention deduce.io as an example

Food for example after wrangling.. all attributes will be integers (indexes in the their master domain tables)

**Comment by JVonderwell** [comment]
added with PR #189
