### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by Ihabilyas** [HoloClean/HoloClean-Legacy-deprecated#178]
(1) Wrangling domains (lex)
(2) Ground truth for food
(3) optimized learning for food 
   (3.a) Faster learning
   (3.b) co-occurance as features as discussed
(4) handle single tuple DC
(5) A way to communicate output to users

**Comment by thodrek** [comment]
+ functionality to reveal "cleaned" dataset by canonicalization of the domain clusters: 
    for now we pick one random value from the cluster later we solve the real string canonicalization per NSF proposal.

**Comment by Ihabilyas** [comment]
Order:
1) Co-occurance as features 

2) Holoclean stable in Husky-test

3) Separate wrangler module with two interfaces
a) Transform (row by row in a DataFrame)
b) Normalize ( Column operation)
both are DF in  DF out and for now produce an output csv
