### ISSUE TITLE
Definitions of cellvalues & cell_domain

### ISSUE THREAD

**Issue by abeer-khan** [HoloClean/HoloClean-Legacy-deprecated#186]
To my understanding,

1. noisycells should represent the list of all noisy cells. This is a list of RandomVar where each element is a noisycell. For example, for the hospital dataset the length of this list is 6140

2. cell_domain (in pruning.py) is a dict representing the domains of all noisy cells. This is a dict with key: cellid*, value: dictionary of domain values (after pruning). However, for the hospital dataset the length of this dict is 8000 (even though there are only 6140 noisycells). In fact, there are 19*1000 = 19,000 total cells so cell_domain can't represent all cells of the dataset or even just the cleancells.

What does cell_domain represent then? Why does it have 8000 elements when there are only 6140 noisycells?

*how is the cellid calculated?

**Comment by gmichalo** [comment]
1. noisycells are a list of noisy cells where each RandomVar is a cells
2. cell_domain is  a dictionary representing the domains of all the cells that we want to use(noisy cells and every clean cell that has an attribute that appear in the dk cells)
