### ISSUE TITLE
Updating reader.py

### ISSUE THREAD

**Issue by gmichalo** [HoloClean/HoloClean-Legacy-deprecated#226]
In line 79 (ix_df = df.rdd.zipWithIndex().map(lambda (row, ix): row + (ix + 1,)).toDF()) we should specify the schema of the dataframe

Benefit: we will be sure that the dataframe has the correct schema

Cost: 15 minutes for the change and for testing

**Comment by JVonderwell** [comment]
TODO: Week of 4/23
