### ISSUE TITLE
Review featurization

### ISSUE THREAD

**Issue by gmichalo** [HoloClean/HoloClean-Legacy-deprecated#23]
Please do a code review for the featurization.py

**Comment by ah89** [comment]
I just reviewed the  code these chabges i think need to : 
1. As you chaged T to init and changed the dataset general name code like
self.dataengine.get_schema('T') should change to correspondnce name
2. The possible value did not pruned base on  table 'Domain' . As we already fixed the schema of table domain no matter by which method you create table Domain , the possible table need to prunned to canndidate values
3. the code creates 2 intermediate table to creates final table which they never call after creating possible value table
4. There are messed internal methods they dont follow order to appear w.r.t. setters and getters
5. The comments generally also not understandable to follow

**Comment by gmichalo** [comment]
All the changes have been made!
