### ISSUE TITLE
Startscripts are missing Shebang

### ISSUE THREAD

**Issue by SebastianSchmidl** [HoloClean/HoloClean-Legacy-deprecated#243]
It tried running the scripts:

- `start_notebook.sh`
- `set_env.sh`

but they were missing Shebang.

## Benefit
One can call `$ ./start_notebook.sh` easily and does not have to worry, which shell to use.

## Cost
Low - couple of minutes.

## Possible solution

Add Shebang to top of scripts, eg. for `start_notebook.sh`:

```bash
#!/usr/bin/env bash

# Set & move to home directory
source set_env.sh
cd "$HOLOCLEANHOME"

# Launch jupyter notebook!
echo "Launching Jupyter Notebook..."
jupyter notebook

```

**Comment by JVonderwell** [comment]
Done with PR #244
