### ISSUE TITLE
Readme update for virtualenv

### ISSUE THREAD

**Issue by SebastianSchmidl** [HoloClean/HoloClean-Legacy-deprecated#245]
I used _virtuelenv_ to install all required python-dependencies for _HoloClean_. There was no documentation for this procedure in the README. Installation with _virtualenv_ was successful, so I want to add it to the README file.

## Benefit
Setup with _virtualenv_ is documented.

## Cost
Low - couple of minutes

**Comment by JVonderwell** [comment]
Done with PR #246
