### ISSUE TITLE
Changes in dataset.py

### ISSUE THREAD

**Issue by thodrek** [HoloClean/HoloClean-Legacy-deprecated#28]
1) biases should be Biases. Consistency

2) Remove line27. I have no idea what is that.

3) So in dataset the moment I want to access a specific table I need to know its id in list attributes? This is not good practice. You convert them to simple members initialized to point to a DB table or DB_table name whatever you have. Update all code that calls Dataset.attributes[id] to use the proper member of the dataset instance.

4) self.table_name[0]=self.dataset_id what is table_name? The code has to be readable

**Comment by ah89** [comment]
In this design if one knows the general name of the table ask dataset with getter table_specific_name() and it return the real table name in database for example if we want the init table specific name for this dataset we call self.table_specific_name('Init') then it return Init_93874346543 which is the real name of init table in data base and is unique
