### ISSUE TITLE
featurization.py

### ISSUE THREAD

**Issue by thodrek** [HoloClean/HoloClean-Legacy-deprecated#33]
Fix typos: one example
1) _query_for_featurization_of_cooncur -> cooccur

Also Class Featurizer should be a template class.
DCFeaturizer
InitValFeaturizer
CooccurFeaturizer

should be different subclasses

We should also have FeaturizationEngine class or something that takes as input a set of featurizers and applies them to the input dataset.

2) Table names are off again. Remove table1 table2 table3 etc. Give them names!

3) Add comments.

**Comment by gmichalo** [comment]
Changes 1,2,3 have been made. We talked with theo and we agreed that for now we should not change the classes. But it should be done in the next phase
