### ISSUE TITLE
DataEngine class

### ISSUE THREAD

**Issue by ah89** [HoloClean/HoloClean-Legacy-deprecated#4]
-**Member**:
jodbc_connector
datasets={}

-**Constructor**:
open connection

-**Methods**:
register dataset (datasetname, schema)
	[create a table in db]
register dataset(datasetnamp)
load(data,dataframe)
retrieve(dataframe, sql_query) [return dataframe]

**Comment by thodrek** [comment]
Update the requirements to ship mysql with HoloClean. Setup connections etc.

**Comment by ah89** [comment]
Done
