### ISSUE TITLE
Dataset Descriptions

### ISSUE THREAD

**Issue by JVonderwell** [HoloClean/HoloClean-Legacy-deprecated#40]
Quite a few tables were added recently with no descriptions in dataset.py. Most are self-explanatory but we should add quick comments to be consistent with what we were doing before.

**Comment by JVonderwell** [comment]
Furthermore, about 5 are referencing numskull and I assume we are no longer using them. 3 separate are specified only for debugging purposes and to be removed. If these are not used anymore we should remove them.

**Comment by jw-mcgrath** [comment]
@JVonderwell @gmichalo What is the status of this? Do we need to get this done before release?
